# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/pablo/OneDrive/Escritorio/Master Granada/1 1 cuatri/Proyecto_V3_FINAL/Proyecto_V3_FINAL.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xci
# IP: The module: 'design_1_proc_sys_reset_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/pablo/OneDrive/Escritorio/Master Granada/1 1 cuatri/Proyecto_V3_FINAL/Proyecto_V3_FINAL.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/pablo/OneDrive/Escritorio/Master Granada/1 1 cuatri/Proyecto_V3_FINAL/Proyecto_V3_FINAL.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/pablo/OneDrive/Escritorio/Master Granada/1 1 cuatri/Proyecto_V3_FINAL/Proyecto_V3_FINAL.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/pablo/OneDrive/Escritorio/Master Granada/1 1 cuatri/Proyecto_V3_FINAL/Proyecto_V3_FINAL.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xci
# IP: The module: 'design_1_proc_sys_reset_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/pablo/OneDrive/Escritorio/Master Granada/1 1 cuatri/Proyecto_V3_FINAL/Proyecto_V3_FINAL.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/pablo/OneDrive/Escritorio/Master Granada/1 1 cuatri/Proyecto_V3_FINAL/Proyecto_V3_FINAL.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/pablo/OneDrive/Escritorio/Master Granada/1 1 cuatri/Proyecto_V3_FINAL/Proyecto_V3_FINAL.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
